apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: paperless
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: paperless
  resourcePolicy:
    containerPolicies:
      - containerName: paperless
        minAllowed:
          memory: 2Gi
  updatePolicy:
    updateMode: InPlaceOrRecreate
