apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: grafana-alloy
spec:
  targetRef:
    apiVersion: apps/v1
    kind: DaemonSet
    name: grafana-alloy
  updatePolicy:
    updateMode: InPlaceOrRecreate
