apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  valuesContent: |-
    args:
      - --kubelet-insecure-tls
      - --kubelet-preferred-address-types=InternalIP
    priorityClassName: system-node-critical
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
