apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  valuesContent: |-
    args:
      - --kubelet-insecure-tls
      - --kubelet-preferred-address-types=InternalIP
